
name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main
    paths:
      - 'saver/**'

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: [self-hosted, linux]

    steps:
      - name: Launch
        run: |
          docker login -u ${{secrets.DOCKER_USERNAME}} -p  ${{secrets.DOCKER_PWD}}
          docker run -d -p 8080:8080 ambroise123/saverrr:latest
            
